export const questions = [
  {
    id: 1,
    type: "multiple",
    text: "Какие свойства описывают реляционную базу данных?",
    options: [
      "Хорошая горизонтальная масштабируемость",
      "Документо-ориентированная модель с индексацией данных",
      "Динамическая схема данных",
      "Строгая таблично-ориентированная модель данных",
      "Возможность вертикальной масштабируемости",
    ],
    correct: [3, 4],
  },
  {
    id: 2,
    type: "single",
    text: "Какие компоненты обязательны при установке MS SQL Server?",
    options: [
      "SQL Server Agent, Integration Services, Database Engine",
      "Reporting Services, Replication, Database Engine",
      "SQL Server Management Tools, Database Engine, Connectivity Components",
      "Integration Services, Database Engine, Analysis Services",
      "Никакой из представленных вариантов",
    ],
    correct: [4],
  },
  {
    id: 3,
    type: "single",
    text: "Нужно дать новому пользователю доступ к новой базе с правами администратора. Выберите правильный вариант действий.",
    options: [
      "Создать логин с ролью public и дать полные права на схему",
      "Создать логин с правами администратора и дать роль sysadmin",
      "Создать пользователя в базе и выдать роль DB_OWNER",
      "Создать логин и добавить в группу системных администраторов SQL Server",
      "Создать пользователя и назначить логин Sa",
    ],
    correct: [2],
  },
  {
    id: 4,
    type: "single",
    text: "Какая оснастка управляет конфигурацией запуска и сетевыми настройками MS SQL Server?",
    options: [
      "MS SQL Server Agent",
      "MS SQL Server Management Studio",
      "MS SQL Server Manager Studio",
      "MS SQL Server Profiler",
      "MS SQL Server Configuration Manager",
    ],
    correct: [4],
  },
  {
    id: 5,
    type: "multiple",
    text: "Выберите средства высокой доступности данных в MS SQL Server 2012.",
    options: [
      "Replication",
      "Database mail",
      "Mirroring",
      "Server Agent",
      "Migration",
      "Reporting",
      "Always On",
      "Log shipping",
    ],
    correct: [0, 2, 6, 7],
  },
  {
    id: 6,
    type: "single",
    text: "Какая база не может быть перемещена командой ALTER DATABASE?",
    options: ["MODEL", "BACKUPS", "MASTER", "MSDB", "TEMPDB"],
    correct: [2],
  },
  {
    id: 7,
    type: "single",
    text: "Выберите оптимальный план резервного копирования для большой активно изменяемой БД.",
    options: [
      "Полная копия в нерабочее время + журналы по bulk-logged",
      "Полные бэкапы в конце года + дифференциальные раз в месяц",
      "Полные в конце недели + дифференциальные ежедневно + журналы в простой модели",
      "Полные в конце недели + журналы только в начале/конце дня",
      "Полные/дифференциальные/журнальные бэкапы в полной модели с периодичностью по RPO/RTO",
    ],
    correct: [4],
  },
  {
    id: 8,
    type: "single",
    text: "Нужно развернуть много одинаковых экземпляров SQL Server для кластера. Лучший подход:",
    options: [
      "Ручная одновременная установка через GUI",
      "Ручная установка всех экземпляров через GUI и конфиг",
      "Система управления конфигурациями + автоматизация ОС и сервисных аккаунтов",
      "Последовательный запуск скрипта по списку серверов",
      "Удаленный доступ и скрипт установки для каждого сервера",
    ],
    correct: [2],
  },
  {
    id: 9,
    type: "single",
    text: "Какие расширения файлов содержат активные данные SQL Server?",
    options: [
      "mdf, ldf, bak",
      "mdf, ldf, ndf",
      "ndf, ldf, dbo",
      "mdb, ldb, ndb",
      "mdf, ldf, sdf",
    ],
    correct: [1],
  },
  {
    id: 10,
    type: "multiple",
    text: "Типы репликации в MS SQL Server 2012:",
    options: [
      "Clustering",
      "Log shipping",
      "Snapshot",
      "Transactional",
      "Merge",
      "Peer-to-peer",
    ],
    correct: [2, 3, 4, 5],
  },
  {
    id: 11,
    type: "single",
    text: "Выберите корректный набор средств мониторинга и поиска неисправностей SQL Server.",
    options: [
      "SQL Audit, SQL Profiler, SSRS reports",
      "Windows Netmon, Event Viewer, SQL Tuning Advisor",
      "Windows Perfmon, Event Viewer, SQL error logs",
      "Windows Perfmon, SQL error logs, Database Engine Tuning Advisor",
      "SQL Agent, SQL Profiler, Extended Events",
      "SQL Audit, SQL Profiler, Extended Events",
    ],
    correct: [5],
  },
  {
    id: 12,
    type: "single",
    text: "Какой сервис слушает входящие подключения и помогает выбрать экземпляр SQL Server?",
    options: [
      "SQL Server Browser Service",
      "SQL Server Agent Service",
      "SQL Server profiler service",
      "SQL Server Database Engine service",
      "SQL Reporting Service",
    ],
    correct: [0],
  },
  {
    id: 13,
    type: "single",
    text: "Что соответствует инкрементальной модели восстановления?",
    options: [
      "Разные бэкапы содержат разную информацию, восстанавливаются последовательно",
      "Все бэкапы содержат одинаковый объем информации",
      "Достаточно восстановить только последний инкрементальный бэкап",
      "Все бэкапы идентичны и зависят от чекпоинтов",
      "Бэкапы нужно восстанавливать параллельно",
    ],
    correct: [0],
  },
  {
    id: 14,
    type: "single",
    text: "Верная последовательность восстановления БД из бэкапов:",
    options: [
      "Latest Full, latest Differential, transaction logs 1..n, latest log, tail-log",
      "Latest Full Copy Only, Differential 1..n, latest Differential, latest log",
      "Latest Differential, latest log, latest Full, tail-log",
      "Latest log, latest Differential, latest Full, tail-log",
      "Latest Full, latest Differential, transaction logs 1..n, latest log",
    ],
    correct: [4],
  },
  {
    id: 15,
    type: "multiple",
    text: "Правильные варианты строки подключения в SQLCMD:",
    options: [
      "sqlcmd -S",
      "sqlcmd -S ComputerA\\instanceB",
      "sqlcmd -S IpcComputerA\\<instancename>",
      "sqlcmd -S ComputerA1691",
      "sqlcmd -S tcp:ComputerA1433",
    ],
    correct: [1],
  },
  {
    id: 16,
    type: "single",
    text: "Какой сервис отвечает за выполнение запланированных административных задач?",
    options: [
      "SQL Server Database Engine service",
      "SQL Reporting Service",
      "SQL Server Browser Service",
      "SQL Server Agent Service",
      "SQL Server profiler service",
    ],
    correct: [3],
  },
  {
    id: 17,
    type: "multiple",
    text: "Системные базы данных, создаваемые при установке SQL Server:",
    options: ["MASTER", "RESOURCES", "MSDB", "TEMP", "BACKUPS"],
    correct: [0, 1, 2],
  },
  {
    id: 18,
    type: "multiple",
    text: "Выберите правильные утверждения:",
    options: [
      "Пользователь БД может существовать без логина экземпляра, но не сможет подключиться",
      "Протокол NAMEOPIPES работает через TCP/IP и интернет",
      "Пользователи роли SYSADMIN имеют полномочия во всех БД как db_owner",
      "Пользователь БД без логина может подключаться к экземпляру",
      "Схема БД служит для управления безопасностью на уровне БД",
    ],
    correct: [0, 2, 4],
  },
  {
    id: 19,
    type: "multiple",
    text: "Свойства, присущие системным БД SQL Server:",
    options: [
      "Хранит конфигурации, права доступа, временные объекты и пользовательские сеансы",
      "Хранит настройки оповещений и расписаний задач SQL Server",
      "Содержит пользовательские аудиторские события и создается при включении аудита",
      "Хранит временные объекты и пересоздается при запуске сервера",
      "Содержит системные процедуры/представления/функции и недоступна для изменений",
    ],
    correct: [1, 3, 4],
  },
  {
    id: 20,
    type: "single",
    text: "Как называется механизм записи изменений в журнал до записи страниц данных на диск?",
    options: [
      "integration data processing",
      "extract transform logging",
      "bulk-logged",
      "point objective recovering",
      "write-ahead logging",
    ],
    correct: [4],
  },
];
